# -*- coding: utf-8 -*-
"""InternVL Signature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueA1Sqjr5Z8vOyy3IiX7rPNdu2cjNDk0
"""

!pip install roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="hIBj3RFHSMyS5SLnZ0gl")
project = rf.workspace("tech-ysdkk").project("signature-detection-hlx8j")
dataset = project.version(1).download("yolov8")

from pathlib import Path
import json
from PIL import Image
from tqdm import tqdm

DATA_ROOT = Path("/content/Signature-Detection-1")
OUT_DIR   = Path("/content/internvl_signature_data")
OUT_DIR.mkdir(parents=True, exist_ok=True)

PROMPT = "Detect and label all signatures in the image. Output each signature with its bounding boxes."
TARGET_LABEL = "signature"

def yolo_to_xyxy(line, W, H):
    parts = line.strip().split()
    if len(parts) != 5:
        return None

    class_id, xc, yc, w, h = parts
    xc, yc, w, h = map(float, [xc, yc, w, h])

    x1 = (xc - w / 2.0) * W
    y1 = (yc - h / 2.0) * H
    x2 = (xc + w / 2.0) * W
    y2 = (yc + h / 2.0) * H

    x1 = max(0, min(x1, W))
    y1 = max(0, min(y1, H))
    x2 = max(0, min(x2, W))
    y2 = max(0, min(y2, H))

    return [x1, y1, x2, y2]

def norm_to_1000(xyxy, W, H):
    x1, y1, x2, y2 = xyxy
    return [
        int(round(x1 / W * 1000)),
        int(round(y1 / H * 1000)),
        int(round(x2 / W * 1000)),
        int(round(y2 / H * 1000)),
    ]

def build_answer(grouped):
    lines = []
    for label, boxes in grouped.items():
        lines.append(f"<ref>{label}</ref><box>{boxes}</box>")
    return "\n".join(lines) + ("\n" if lines else "")

def convert_split(split_name: str):
    images_dir = DATA_ROOT / split_name / "images"
    labels_dir = DATA_ROOT / split_name / "labels"

    if not images_dir.exists():
        raise FileNotFoundError(f"Missing images directory: {images_dir}")
    if not labels_dir.exists():
        raise FileNotFoundError(f"Missing labels directory: {labels_dir}")

    image_paths = []
    for ext in ["*.jpg", "*.jpeg", "*.png", "*.bmp", "*.webp"]:
        image_paths.extend(images_dir.glob(ext))
    image_paths = sorted(image_paths)

    out_jsonl = OUT_DIR / f"{split_name}.jsonl"
    n = 0

    with out_jsonl.open("w", encoding="utf-8") as f:
        for idx, img_path in enumerate(tqdm(image_paths, desc=f"Convert {split_name}")):
            with Image.open(img_path) as im:
                W, H = im.size

            label_path = labels_dir / f"{img_path.stem}.txt"
            grouped = {}

            if label_path.exists():
                raw = label_path.read_text(encoding="utf-8").strip()
                if raw:
                    boxes = []
                    for line in raw.splitlines():
                        parsed = yolo_to_xyxy(line, W, H)
                        if parsed is None:
                            continue
                        boxn = norm_to_1000(parsed, W, H)
                        boxes.append(boxn)

                    if boxes:
                        grouped[TARGET_LABEL] = boxes

            rel_image = f"{split_name}/images/{img_path.name}"
            answer = build_answer(grouped)

            sample = {
                "id": f"{split_name}_{idx}",
                "image": rel_image,
                "width": int(W),
                "height": int(H),
                "conversations": [
                    {"from": "human", "value": f"<image>\n{PROMPT}"},
                    {"from": "gpt", "value": answer if answer.strip() else "No signatures found.\n"},
                ],
            }

            f.write(json.dumps(sample, ensure_ascii=False) + "\n")
            n += 1

    return out_jsonl, n

train_jsonl, n_train = convert_split("train")
valid_jsonl, n_valid = convert_split("valid")
test_jsonl,  n_test  = convert_split("test")

print("JSONL written:")
print(train_jsonl, n_train)
print(valid_jsonl, n_valid)
print(test_jsonl, n_test)

meta = {
    "signature_train": {
        "root": str(DATA_ROOT),
        "annotation": str(train_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_train,
    },
    "signature_valid": {
        "root": str(DATA_ROOT),
        "annotation": str(valid_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_valid,
    },
    "signature_test": {
        "root": str(DATA_ROOT),
        "annotation": str(test_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_test,
    },
}

meta_path = OUT_DIR / "meta.json"
meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
print("meta.json saved to:", meta_path)

import json
import re
import ast
import random
from pathlib import Path

from PIL import Image, ImageFile
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Avoid issues with very large images
Image.MAX_IMAGE_PIXELS = None
ImageFile.LOAD_TRUNCATED_IMAGES = True

JSONL_PATH = Path("/content/internvl_signature_data/train.jsonl")
DATA_ROOT  = Path("/content/Signature-Detection-1")

REFBOX_RE = re.compile(r"<ref>(.*?)</ref>\s*<box>(.*?)</box>", re.DOTALL)

def parse_refbox(answer_text):
    pairs = []
    for label, box_str in REFBOX_RE.findall(answer_text):
        try:
            boxes = ast.literal_eval(box_str)
            pairs.append((label.strip(), boxes))
        except Exception:
            continue
    return pairs

def denorm_1000_to_pixels(box, W, H):
    x1, y1, x2, y2 = box
    return [
        x1 / 1000.0 * W,
        y1 / 1000.0 * H,
        x2 / 1000.0 * W,
        y2 / 1000.0 * H,
    ]

# Load all samples
lines = JSONL_PATH.read_text(encoding="utf-8").splitlines()
samples = [json.loads(line) for line in lines]

# Keep only samples that actually contain signatures
samples_with_signatures = [
    s for s in samples
    if "<ref>signature</ref>" in s["conversations"][1]["value"]
]

print(f"Total samples: {len(samples)}")
print(f"Samples with signatures: {len(samples_with_signatures)}")

# Number of examples to display
N = 6
chosen_samples = random.sample(samples_with_signatures, min(N, len(samples_with_signatures)))

for i, sample in enumerate(chosen_samples, 1):
    img_path = DATA_ROOT / sample["image"]
    img = Image.open(img_path).convert("RGB")
    W, H = img.size

    answer = sample["conversations"][1]["value"]
    pairs = parse_refbox(answer)

    plt.figure(figsize=(10, 10))
    plt.imshow(img)
    ax = plt.gca()

    for label, boxes in pairs:
        for b in boxes:
            x1, y1, x2, y2 = denorm_1000_to_pixels(b, W, H)

            rect = patches.Rectangle(
                (x1, y1),
                x2 - x1,
                y2 - y1,
                fill=False,
                linewidth=2
            )
            ax.add_patch(rect)

            ax.text(
                x1,
                max(0, y1 - 5),
                "signature",
                fontsize=10,
                bbox=dict(facecolor="white", alpha=0.7)
            )

    plt.title(f"Sample {i}: {sample['image']}")
    plt.axis("off")
    plt.show()

"""Fine-tuning"""

!pip -q uninstall -y roboflow gradio pi-heif
!pip -q uninstall -y pillow Pillow
!pip -q install --no-cache-dir "pillow==11.1.0"

!pip -q uninstall -y transformers tokenizers safetensors accelerate huggingface-hub peft
!pip -q install --no-cache-dir "transformers>=4.55.0" "peft>=0.13.0" accelerate huggingface-hub safetensors sentencepiece datasets trl bitsandbytes

from pathlib import Path
import json
from PIL import Image
from tqdm import tqdm

DATA_ROOT = Path("/content/Signature-Detection-1")
OUT_DIR   = Path("/content/internvl_signature_data")
OUT_DIR.mkdir(parents=True, exist_ok=True)

PROMPT = "Detect and label all signatures in the image. Output each signature with its bounding boxes."
TARGET_LABEL = "signature"

def yolo_to_xyxy(line, W, H):
    parts = line.strip().split()
    if len(parts) != 5:
        return None

    class_id, xc, yc, w, h = parts
    xc, yc, w, h = map(float, [xc, yc, w, h])

    x1 = (xc - w / 2.0) * W
    y1 = (yc - h / 2.0) * H
    x2 = (xc + w / 2.0) * W
    y2 = (yc + h / 2.0) * H

    x1 = max(0, min(x1, W))
    y1 = max(0, min(y1, H))
    x2 = max(0, min(x2, W))
    y2 = max(0, min(y2, H))

    return [x1, y1, x2, y2]

def norm_to_1000(xyxy, W, H):
    x1, y1, x2, y2 = xyxy
    return [
        int(round(x1 / W * 1000)),
        int(round(y1 / H * 1000)),
        int(round(x2 / W * 1000)),
        int(round(y2 / H * 1000)),
    ]

def build_answer(grouped):
    lines = []
    for label, boxes in grouped.items():
        lines.append(f"<ref>{label}</ref><box>{boxes}</box>")
    return "\n".join(lines) + ("\n" if lines else "")

def convert_split(split_name: str):
    images_dir = DATA_ROOT / split_name / "images"
    labels_dir = DATA_ROOT / split_name / "labels"

    if not images_dir.exists():
        raise FileNotFoundError(f"Missing images directory: {images_dir}")
    if not labels_dir.exists():
        raise FileNotFoundError(f"Missing labels directory: {labels_dir}")

    image_paths = []
    for ext in ["*.jpg", "*.jpeg", "*.png", "*.bmp", "*.webp"]:
        image_paths.extend(images_dir.glob(ext))
    image_paths = sorted(image_paths)

    out_jsonl = OUT_DIR / f"{split_name}.jsonl"
    n = 0

    with out_jsonl.open("w", encoding="utf-8") as f:
        for idx, img_path in enumerate(tqdm(image_paths, desc=f"Convert {split_name}")):
            with Image.open(img_path) as im:
                W, H = im.size

            label_path = labels_dir / f"{img_path.stem}.txt"
            grouped = {}

            if label_path.exists():
                raw = label_path.read_text(encoding="utf-8").strip()
                if raw:
                    boxes = []
                    for line in raw.splitlines():
                        parsed = yolo_to_xyxy(line, W, H)
                        if parsed is None:
                            continue
                        boxn = norm_to_1000(parsed, W, H)
                        boxes.append(boxn)

                    if boxes:
                        grouped[TARGET_LABEL] = boxes

            rel_image = f"{split_name}/images/{img_path.name}"
            answer = build_answer(grouped)

            sample = {
                "id": f"{split_name}_{idx}",
                "image": rel_image,
                "width": int(W),
                "height": int(H),
                "conversations": [
                    {"from": "human", "value": f"<image>\n{PROMPT}"},
                    {"from": "gpt", "value": answer if answer.strip() else "No signatures found.\n"},
                ],
            }

            f.write(json.dumps(sample, ensure_ascii=False) + "\n")
            n += 1

    return out_jsonl, n

train_jsonl, n_train = convert_split("train")
valid_jsonl, n_valid = convert_split("valid")
test_jsonl,  n_test  = convert_split("test")

print("JSONL written:")
print(train_jsonl, n_train)
print(valid_jsonl, n_valid)
print(test_jsonl, n_test)

meta = {
    "signature_train": {
        "root": str(DATA_ROOT),
        "annotation": str(train_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_train,
    },
    "signature_valid": {
        "root": str(DATA_ROOT),
        "annotation": str(valid_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_valid,
    },
    "signature_test": {
        "root": str(DATA_ROOT),
        "annotation": str(test_jsonl),
        "data_augment": False,
        "max_dynamic_patch": 12,
        "repeat_time": 1,
        "length": n_test,
    },
}

meta_path = OUT_DIR / "meta.json"
meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
print("meta.json saved to:", meta_path)

from google.colab import drive
drive.mount("/content/drive")

# --------------------------------------------------
# 1) Unzip the signature LoRA adapter from Google Drive
# --------------------------------------------------
LORA_ZIP = "/content/drive/MyDrive/internvl_vision_LORA_signature_ft.zip"
LORA_OUT = "/content/internvl_vision_LORA_signature_ft"

!rm -rf "{LORA_OUT}"
!mkdir -p "{LORA_OUT}"
!unzip -q "{LORA_ZIP}" -d "{LORA_OUT}"

print("LoRA adapter unzipped to:", LORA_OUT)
!find "{LORA_OUT}" -type f -print

# --------------------------------------------------
# 2) Load base InternVL3.5 from Hugging Face
# --------------------------------------------------
import os
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
from peft import PeftModel

MODEL_ID = "OpenGVLab/InternVL3_5-4B-HF"

cap_major, cap_minor = torch.cuda.get_device_capability(0)
use_bf16 = torch.cuda.is_available() and cap_major >= 8
dtype = torch.bfloat16 if use_bf16 else torch.float16

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
)

model = AutoModelForImageTextToText.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    torch_dtype=dtype,
    low_cpu_mem_usage=True,
)

model = model.cuda() if torch.cuda.is_available() else model.cpu()

# --------------------------------------------------
# 3) IMPORTANT: set the real adapter path after inspecting !find output
# --------------------------------------------------
ADAPTER_DIR = "/content/internvl_vision_LORA_signature_ft/final"   # change if needed after inspecting output

print("ADAPTER exists:", os.path.exists(ADAPTER_DIR))
print("ADAPTER files:", os.listdir(ADAPTER_DIR))

# --------------------------------------------------
# 4) Load LoRA weights and continue fine-tuning
# --------------------------------------------------
model = PeftModel.from_pretrained(
    model,
    ADAPTER_DIR,
    is_trainable=True,
)

model.config.use_cache = False
model.train()

print("Loaded base:", MODEL_ID)
print("Loaded adapter:", ADAPTER_DIR)
print("dtype:", dtype)

try:
    model.print_trainable_parameters()
except Exception:
    pass

import json
from pathlib import Path
from PIL import Image, ImageFile
from torch.utils.data import Dataset

Image.MAX_IMAGE_PIXELS = None
ImageFile.LOAD_TRUNCATED_IMAGES = True

DATA_ROOT = Path("/content/Signature-Detection-1")
INTERNVL_DIR = Path("/content/internvl_signature_data")

TRAIN_JSONL = INTERNVL_DIR / "train.jsonl"
VALID_JSONL = INTERNVL_DIR / "valid.jsonl"
TEST_JSONL  = INTERNVL_DIR / "test.jsonl"

assert TRAIN_JSONL.exists(), f"Missing {TRAIN_JSONL}"

IMAGE_TOKEN = None
for attr in ["image_token", "image_placeholder", "image_tag"]:
    if hasattr(processor, attr):
        IMAGE_TOKEN = getattr(processor, attr)
        break

if IMAGE_TOKEN is None and hasattr(processor, "tokenizer"):
    for attr in ["image_token", "img_token", "image_placeholder", "start_image_token"]:
        if hasattr(processor.tokenizer, attr):
            IMAGE_TOKEN = getattr(processor.tokenizer, attr)
            break

if IMAGE_TOKEN is None:
    IMAGE_TOKEN = "<image>"

print("Using IMAGE_TOKEN =", repr(IMAGE_TOKEN))

class InternVLDataset(Dataset):
    def __init__(self, jsonl_path: Path, image_token: str):
        self.rows = [json.loads(l) for l in jsonl_path.read_text(encoding="utf-8").splitlines()]
        self.image_token = image_token

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        r = self.rows[idx]
        img_path = DATA_ROOT / r["image"]
        image = Image.open(img_path).convert("RGB")

        prompt = r["conversations"][0]["value"]
        prompt = prompt.replace("<image>", self.image_token)

        if self.image_token not in prompt:
            prompt = f"{self.image_token}\n" + prompt

        while prompt.count(self.image_token) > 1:
            first = prompt.find(self.image_token)
            second = prompt.find(self.image_token, first + len(self.image_token))
            prompt = prompt[:second] + prompt[second + len(self.image_token):]

        answer = r["conversations"][1]["value"]
        return {"image": image, "prompt": prompt, "answer": answer}

train_ds = InternVLDataset(TRAIN_JSONL, IMAGE_TOKEN)
valid_ds = InternVLDataset(VALID_JSONL, IMAGE_TOKEN) if VALID_JSONL.exists() else None
test_ds  = InternVLDataset(TEST_JSONL, IMAGE_TOKEN) if TEST_JSONL.exists() else None

print("Train samples:", len(train_ds))
print("Valid samples:", len(valid_ds) if valid_ds else 0)
print("Test samples:", len(test_ds) if test_ds else 0)

def collate_fn(batch, processor):
    images  = [b["image"] for b in batch]
    prompts = [b["prompt"] for b in batch]
    answers = [b["answer"] for b in batch]

    enc_prompt = processor(
        text=prompts,
        images=images,
        return_tensors="pt",
        padding=True,
    )

    full_text = [p + a for p, a in zip(prompts, answers)]
    enc_full = processor(
        text=full_text,
        images=images,
        return_tensors="pt",
        padding=True,
    )

    input_ids = enc_full["input_ids"]
    attention_mask = enc_full["attention_mask"]
    labels = input_ids.clone()

    prompt_lens = enc_prompt["attention_mask"].sum(dim=1).tolist()
    for i, L in enumerate(prompt_lens):
        labels[i, :L] = -100

    out = {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

    if "pixel_values" in enc_full:
        out["pixel_values"] = enc_full["pixel_values"]

    return out

for name, module in model.named_modules():
    if "vision_tower" in name and isinstance(module, torch.nn.Linear):
        print(name)

import math, torch
from transformers import TrainingArguments, Trainer
import os

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

model.config.use_cache = False
if hasattr(model, "gradient_checkpointing_enable"):
    model.gradient_checkpointing_enable()

cap_major, cap_minor = torch.cuda.get_device_capability(0)
use_bf16 = cap_major >= 8
use_fp16 = not use_bf16

EPOCHS = 2
BATCH = 1
ACCUM = 16
LR = 2e-4

steps_per_epoch = math.ceil(len(train_ds) / (BATCH * ACCUM))
total_steps = steps_per_epoch * EPOCHS
warmup_steps = max(10, int(0.03 * total_steps))

args = TrainingArguments(
    output_dir="/content/internvl3_5_signature_lora_vit",
    per_device_train_batch_size=BATCH,
    gradient_accumulation_steps=ACCUM,
    learning_rate=LR,
    warmup_steps=warmup_steps,
    num_train_epochs=EPOCHS,
    logging_strategy="epoch",
    bf16=use_bf16,
    fp16=use_fp16,
    bf16_full_eval=use_bf16,
    prediction_loss_only=True,
    remove_unused_columns=False,
    report_to="none",
    optim="paged_adamw_8bit",
    save_strategy="epoch",
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=valid_ds if valid_ds else None,
    data_collator=lambda b: collate_fn(b, processor),
)

trainer.train()

SAVE_DIR = Path("/content/internvl_vision_LORA_signature_ft/final")
SAVE_DIR.mkdir(parents=True, exist_ok=True)

trainer.save_model(str(SAVE_DIR))
processor.save_pretrained(str(SAVE_DIR))

print("Saved to:", SAVE_DIR)

import shutil

folder = "/content/internvl_vision_LORA_signature_ft"         # the folder you want
zip_base = "/content/internvl_vision_LORA_signature_ft"       # output without ".zip"

shutil.make_archive(zip_base, "zip", folder)       # creates /content/internvl_visionLORA_ft.zip

from google.colab import files
files.download("/content/internvl_vision_LORA_signature_ft.zip")

import re, ast, torch, random
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

REFBOX_RE = re.compile(r"<ref>(.*?)</ref>\s*<box>(.*?)</box>", re.DOTALL)
PLAIN_RE = re.compile(r"(signature)\s*(\[\[.*?\]\])", re.DOTALL | re.IGNORECASE)

def parse_boxes(text):
    out = []

    # Format 1: <ref>signature</ref><box>[[...], [...]]</box>
    for label, box_str in REFBOX_RE.findall(text):
        try:
            boxes = ast.literal_eval(box_str)
            out.append((label.strip().lower(), boxes))
        except Exception:
            pass

    if out:
        return out

    # Format 2: signature[[...], [...]]
    m = PLAIN_RE.search(text)
    if m:
        label = m.group(1).strip().lower()
        box_str = m.group(2)
        try:
            boxes = ast.literal_eval(box_str)
            out.append((label, boxes))
        except Exception:
            pass

    return out

def denorm_1000_to_pixels(box, W, H):
    x1, y1, x2, y2 = box
    return [x1 / 1000 * W, y1 / 1000 * H, x2 / 1000 * W, y2 / 1000 * H]

def predict_answer(image, prompt, max_new_tokens=256):
    inputs = processor(
        text=prompt,
        images=[image],
        return_tensors="pt",
        padding=True,
    )
    inputs = {k: v.to(model.device) if torch.is_tensor(v) else v for k, v in inputs.items()}
    input_len = inputs["input_ids"].shape[1]

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=1,
        )

    gen_ids = output_ids[:, input_len:]
    pred_text = processor.batch_decode(gen_ids, skip_special_tokens=True)[0]

    # Keep only the useful first part if the model continues generating junk
    pred_text = pred_text.split("```")[0].strip()

    return pred_text

# choose dataset
ds = test_ds if test_ds is not None else valid_ds

# visualize a few random samples
num_samples = 25
indices = random.sample(range(len(ds)), min(num_samples, len(ds)))

model.eval()

for idx in indices:
    sample = ds[idx]
    image = sample["image"]
    prompt = sample["prompt"]
    gt_text = sample["answer"]

    pred_text = predict_answer(image, prompt)

    W, H = image.size
    gt_pairs = parse_boxes(gt_text)
    pred_pairs = parse_boxes(pred_text)

    plt.figure(figsize=(10, 10))
    plt.imshow(image)
    ax = plt.gca()

    # Ground truth in red
    for label, boxes in gt_pairs:
        for b in boxes:
            x1, y1, x2, y2 = denorm_1000_to_pixels(b, W, H)
            rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1, fill=False, linewidth=2, edgecolor="red")
            ax.add_patch(rect)
            ax.text(
                x1,
                max(0, y1 - 5),
                "GT: signature",
                fontsize=10,
                bbox=dict(facecolor="white", alpha=0.7)
            )

    # Predictions in green dashed
    for label, boxes in pred_pairs:
        for b in boxes:
            x1, y1, x2, y2 = denorm_1000_to_pixels(b, W, H)
            rect = patches.Rectangle(
                (x1, y1),
                x2 - x1,
                y2 - y1,
                fill=False,
                linewidth=2,
                linestyle="--",
                edgecolor="green"
            )
            ax.add_patch(rect)
            ax.text(
                x1,
                min(H - 5, y2 + 12),
                "Pred: signature",
                fontsize=10,
                bbox=dict(facecolor="white", alpha=0.7)
            )

    plt.title(f"Sample {idx}\nRed = GT, Green dashed = Prediction")
    plt.axis("off")
    plt.show()

    print("GROUND TRUTH:\n", gt_text)
    print("\nPREDICTION:\n", pred_text)
    print("-" * 100)

# model.train()

import numpy as np

def calculate_iou(box1, box2):
    # box format: [x1, y1, x2, y2]
    x1_inter = max(box1[0], box2[0])
    y1_inter = max(box1[1], box2[1])
    x2_inter = min(box1[2], box2[2])
    y2_inter = min(box1[3], box2[3])

    inter_width = max(0, x2_inter - x1_inter)
    inter_height = max(0, y2_inter - y1_inter)
    intersection_area = inter_width * inter_height

    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    union_area = box1_area + box2_area - intersection_area

    if union_area == 0:
        return 0.0
    return intersection_area / union_area

def calculate_metrics(gt_pairs, pred_pairs, iou_threshold=0.5):
    TP = 0
    FP = 0
    FN = 0

    flat_gt_boxes = []
    for label, boxes_list in gt_pairs:
        for box in boxes_list:
            flat_gt_boxes.append(box)

    flat_pred_boxes = []
    for label, boxes_list in pred_pairs:
        for box in boxes_list:
            flat_pred_boxes.append(box)

    if not flat_gt_boxes and not flat_pred_boxes:
        return {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'TP': 0, 'FP': 0, 'FN': 0}
    if not flat_gt_boxes and flat_pred_boxes:
        return {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'TP': 0, 'FP': len(flat_pred_boxes), 'FN': 0}
    if flat_gt_boxes and not flat_pred_boxes:
        return {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'TP': 0, 'FP': 0, 'FN': len(flat_gt_boxes)}

    matched_gt = [False] * len(flat_gt_boxes)

    # Match predictions to ground truth
    for i, p_box in enumerate(flat_pred_boxes):
        best_iou = 0.0
        best_gt_idx = -1
        for j, gt_box in enumerate(flat_gt_boxes):
            if not matched_gt[j]:
                iou = calculate_iou(p_box, gt_box)
                if iou > best_iou:
                    best_iou = iou
                    best_gt_idx = j

        if best_iou >= iou_threshold:
            TP += 1
            matched_gt[best_gt_idx] = True
        else:
            FP += 1

    FN = len(flat_gt_boxes) - sum(matched_gt)

    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

    return {'precision': precision, 'recall': recall, 'f1': f1, 'TP': TP, 'FP': FP, 'FN': FN}

# Assume model is already in eval mode from the previous display cell
# If not, uncomment model.eval() below.
# model.eval()

all_metrics = []

# Evaluate on the 'ds' which is test_ds or valid_ds
# Limiting to 100 samples for quicker execution, adjust as needed
num_eval_samples = min(len(ds), 200) # Evaluate on max 100 samples

# Select random indices for evaluation if ds is large
if len(ds) > num_eval_samples:
    eval_indices = random.sample(range(len(ds)), num_eval_samples)
    eval_samples = [ds[i] for i in eval_indices]
else:
    eval_samples = ds

print(f"\nEvaluating model on {len(eval_samples)} samples...")

for idx, sample in enumerate(eval_samples):
    image = sample["image"]
    prompt = sample["prompt"]
    gt_text = sample["answer"]

    pred_text = predict_answer(image, prompt)

    W, H = image.size
    gt_pairs = parse_boxes(gt_text)
    pred_pairs = parse_boxes(pred_text)

    # Denormalize boxes to pixel coordinates for metric calculation
    denorm_gt_pairs = []
    for label, boxes_list in gt_pairs:
        denorm_boxes = [denorm_1000_to_pixels(b, W, H) for b in boxes_list]
        denorm_gt_pairs.append((label, denorm_boxes))

    denorm_pred_pairs = []
    for label, boxes_list in pred_pairs:
        denorm_boxes = [denorm_1000_to_pixels(b, W, H) for b in boxes_list]
        denorm_pred_pairs.append((label, denorm_boxes))

    metrics = calculate_metrics(denorm_gt_pairs, denorm_pred_pairs, iou_threshold=0.5)
    all_metrics.append(metrics)

# Aggregate metrics
total_TP = sum(m['TP'] for m in all_metrics)
total_FP = sum(m['FP'] for m in all_metrics)
total_FN = sum(m['FN'] for m in all_metrics)

avg_precision = total_TP / (total_TP + total_FP) if (total_TP + total_FP) > 0 else 0.0
avg_recall = total_TP / (total_TP + total_FN) if (total_TP + total_FN) > 0 else 0.0
avg_f1 = 2 * (avg_precision * avg_recall) / (avg_precision + avg_recall) if (avg_precision + avg_recall) > 0 else 0.0

print(f"\n--- Aggregated Metrics for {len(eval_samples)} samples ---")
print(f"Total True Positives: {total_TP}")
print(f"Total False Positives: {total_FP}")
print(f"Total False Negatives: {total_FN}")
print(f"Overall Precision: {avg_precision:.4f}")
print(f"Overall Recall: {avg_recall:.4f}")
print(f"Overall F1-Score: {avg_f1:.4f}")

"""Test on BNP Paribas"""

!pip install pymupdf pillow

use_cuda = torch.cuda.is_available()

def move_inputs_to_device(inputs, model, use_cuda):
    target_device = model.device if use_cuda else torch.device("cpu")
    out = {}
    for k, v in inputs.items():
        if torch.is_tensor(v):
            out[k] = v.to(target_device)
        else:
            out[k] = v
    return out


def predict_on_image(image, user_text, max_new_tokens=256):
    prompt = f"<IMG_CONTEXT>\n{user_text}"

    inputs = processor(
        text=prompt,
        images=[image],
        return_tensors="pt"
    )

    target_device = model.device if torch.cuda.is_available() else torch.device("cpu")
    inputs = {
        k: v.to(target_device) if torch.is_tensor(v) else v
        for k, v in inputs.items()
    }

    input_len = inputs["input_ids"].shape[1]

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            num_beams=1,
            temperature=None,
            top_p=None,
            repetition_penalty=1.1,
            eos_token_id=processor.tokenizer.eos_token_id,
            pad_token_id=processor.tokenizer.eos_token_id,
        )

    new_tokens = output_ids[:, input_len:]
    pred = processor.batch_decode(new_tokens, skip_special_tokens=True)[0].strip()
    return pred

USER_TEXT = """Detect signatures.
Return only JSON.
Format:
[
  {"label":"signature","bbox":[x1,y1,x2,y2],"text":"..."},
]
If none, return [].
Do not explain."""

import re
import ast
import fitz  # PyMuPDF
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

PDF_PATH = "/content/Annual report sample.pdf"   # change this
PAGE_NUM = 1                                   # 1-based page number
ZOOM = 2.0

def pdf_page_to_pil(pdf_path, page_idx=0, zoom=2.0):
    doc = fitz.open(pdf_path)
    page = doc[page_idx]
    mat = fitz.Matrix(zoom, zoom)
    pix = page.get_pixmap(matrix=mat, alpha=False)
    img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
    doc.close()
    return img

def parse_pred_boxes(text):
    text = text.strip()

    # Keep only JSON-ish part if extra text is generated
    start = text.find("[")
    end = text.rfind("]")
    if start != -1 and end != -1 and end > start:
        candidate = text[start:end + 1]
    else:
        candidate = text

    out = []

    # Parse list of dicts
    try:
        data = ast.literal_eval(candidate)
        if isinstance(data, list):
            for obj in data:
                if isinstance(obj, dict) and "bbox" in obj and "label" in obj:
                    bbox = obj["bbox"]
                    label = str(obj["label"])
                    if isinstance(bbox, (list, tuple)) and len(bbox) == 4:
                        out.append((label, list(map(float, bbox))))
            return out
    except Exception:
        pass

    # Fallback: detect {"label":"...","bbox":[...]} patterns
    pattern = re.compile(
        r'"label"\s*:\s*"([^"]+)"\s*,\s*"bbox"\s*:\s*\[([^\]]+)\]',
        re.IGNORECASE | re.DOTALL
    )
    for label, bbox_str in pattern.findall(text):
        try:
            bbox = [float(x.strip()) for x in bbox_str.split(",")]
            if len(bbox) == 4:
                out.append((label, bbox))
        except Exception:
            pass

    return out

def maybe_denorm_bbox(bbox, W, H):
    x1, y1, x2, y2 = bbox

    # If model outputs normalized coords in [0,1000], convert to pixels
    if max(x1, y1, x2, y2) <= 1000:
        return [
            x1 / 1000.0 * W,
            y1 / 1000.0 * H,
            x2 / 1000.0 * W,
            y2 / 1000.0 * H,
        ]

    # Otherwise assume already pixel coords
    return [x1, y1, x2, y2]

page_idx = PAGE_NUM - 1
image = pdf_page_to_pil(PDF_PATH, page_idx=page_idx, zoom=ZOOM)

pred = predict_on_image(image, USER_TEXT, max_new_tokens=256)
parsed = parse_pred_boxes(pred)

print(f"=== PAGE {PAGE_NUM} ===")
print(pred)
print("\nParsed boxes:", parsed)

W, H = image.size

plt.figure(figsize=(10, 14))
plt.imshow(image)
ax = plt.gca()

for label, bbox in parsed:
    x1, y1, x2, y2 = maybe_denorm_bbox(bbox, W, H)

    rect = patches.Rectangle(
        (x1, y1),
        x2 - x1,
        y2 - y1,
        fill=False,
        linewidth=2,
        edgecolor="green"
    )
    ax.add_patch(rect)
    ax.text(
        x1,
        max(0, y1 - 5),
        label,
        fontsize=10,
        bbox=dict(facecolor="white", alpha=0.7)
    )

plt.title(f"Page {PAGE_NUM}")
plt.axis("off")
plt.show()

